Repository konflux-ci/architecture, pull requests merged in 2024-05, with the labels that each got.

#185 feat: add a stale issues and prs pruner
  .github/workflows/stale.yml
Labels: kind/ci

#186 Add a PR size labeler
  .github/workflows/labeler.yml
Labels: kind/ci

#180 Replace most mentions of AppStudio with Konflux
  ADR/0003-interacting-with-internal-services.md
  ADR/0006-log-conventions.md
  ADR/0008-environment-provisioning.md
  ADR/0010-namespace-metadata.md
  ADR/0011-roles-and-permissions.md
  ADR/0012-namespace-name-format.md
  ADR/0013-integration-service-api-contracts.md
  ADR/0014-let-pipelines-proceed.md
  ADR/0016-integration-service-promotion-logic.md
  ADR/0017-use-our-pipelines.md
  ADR/0018-apps-continuous-perf-testing.md
  ADR/0019-customize-url-github.md
  ADR/0020-source-retention.md
  ADR/0025-appstudio-pipeline-serviceaccount.md
  ADR/0026-specifying-ocp-targets-for-fbc.md
  ADR/0027-availability-probe-framework.md
  ADR/0027-container-images.md
  ADR/0029-component-dependencies.md
  ADR/0030-tekton-results-naming-convention.md
  ADR/0031-sprayproxy.md
  ADR/0032-decoupling-deployment.md
  README.md
  _config.yml
  architecture/HAS/hybrid-application-service-api.md
  architecture/HAS/hybrid-application-service-component-types.md
  architecture/HAS/hybrid-application-service-crds.md
  architecture/HAS/hybrid-application-service-design.md
  architecture/HAS/hybrid-application-service-glossary.md
  architecture/enterprise-contract.md
  architecture/hybrid-application-service.md
  architecture/image-controller.md
  architecture/index.md
  architecture/integration-service.md
  architecture/internal-services.md
  architecture/jvm-build-service.md
  architecture/release-service.md
  diagrams/index.md
  diagrams/konflux-workspace-layout.drawio.svg
  diagrams/konflux.drawio.svg
  diagrams/personal-data.drawio.svg
  diagrams/release-service/konflux-release-service-data-flow.jpg
  ref/index.md
  tools/security-tools.MD
Labels: kind/chore

#166 feat(RHTAPWATCH-782): Add product version controller ADR
  ADR/0034-project-controller-for-multiversion.md
Labels: kind/feat
